// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TranThiLanAnh114.Data;

namespace TranThiLanAnh114.Migrations
{
    [DbContext(typeof(LanAnhDBContext))]
    [Migration("20211215062931_Create_Table_TTLA1114s")]
    partial class Create_Table_TTLA1114s
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("TranThiLanAnh114.Models.TTLA1114", b =>
                {
                    b.Property<string>("TTLAId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TTLAGener")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TTLAName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TTLAId");

                    b.ToTable("TTLA1114s");
                });

            modelBuilder.Entity("TranThiLanAnh114.Models.UniversityTTLA114", b =>
                {
                    b.Property<string>("UniversityID")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversityName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UniversityID");

                    b.ToTable("Universitys");
                });
#pragma warning restore 612, 618
        }
    }
}
