// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TranThiLanAnh114.Data;
namespace TranThiLanAnh114.Migrations
{
    [DbContext(typeof(LanAnhDBContext))]
    [Migration("20211215061712_Create_Table_Universitys")]
    partial class Create_Table_Universitys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("TranThiLanAnh114.Models.UniversityTTLA114", b =>
                {
                    b.Property<string>("UniversityID")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversityName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UniversityID");

                    b.ToTable("Universitys");
                });
#pragma warning restore 612, 618
        }
    }
}
